### Cadastro de usuário 
POST https://projectverzel.herokuapp.com/signup 
Content-Type: application/json

{
"nome":"Igor", "email":"igor@gmail.com", "senha":"123456"
}

### Login 
POST https://projectverzel.herokuapp.com/login 
Content-Type: application/json

{
"email":"leozbroca@gmail.com", "senha":"123456"
}

### Cadastro de carros
POST https://projectverzel.herokuapp.com/signupCar
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUzYjkyZjBmLWRjM2MtNDNjMy1hZWIyLWM5MzVmZTExZmZlNiIsImlhdCI6MTY2NzMwMjM0NSwiZXhwIjoxNjY3Mzg4NzQ1fQ.L4NcDuyYVN5vceyzSccWuGK_eSK3mlYQkjE7pl6DBn4

{
"nome":"carrdo", "marca":"citroen", "modelo":"1233", "ano": "2022", "foto":"foto"
}

### Editar carro
PUT https://projectverzel.herokuapp.com/editCar/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNkMTI4NWFkLTIyOWEtNGI4YS04ZDEwLTgzMmJiN2I5Mjk5YSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NzI2MzMwMSwiZXhwIjoxNjY3MzQ5NzAxfQ.JFArpaND8VDAAL5jCG5Wqs7K7iZYRXlUJsBbcVAPDQo

{
"marca":"TESLA", "ano":"1500"
}


### Deletar carro
DELETE http://localhost:3003/deleteCar/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNkMTI4NWFkLTIyOWEtNGI4YS04ZDEwLTgzMmJiN2I5Mjk5YSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NzI2MzMwMSwiZXhwIjoxNjY3MzQ5NzAxfQ.JFArpaND8VDAAL5jCG5Wqs7K7iZYRXlUJsBbcVAPDQo

### Pegar informações de todos os carros
GET https://projectverzel.herokuapp.com/allCars
Content-Type: application/json

### Pegar informações de carros do usuário
GET https://projectverzel.herokuapp.com/getMyCars
Content-Type: application/json

{
"email":"igor@gmail.com"
}